In [1]:
import pandas as pd

In [2]:
ds = pd .read_csv('Pokemon.csv')

In [3]:
ds.head(n=10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [12]:
avg_speed= ds["Speed"].mean()
avg_speed

68.2775

In [13]:
avg_hp = ds["HP"].mean()
avg_hp

69.25875

In [17]:
def set_speed_values(val):
    if val < avg_speed:
        return "Low Speed"
    elif val == avg_speed:
        return "Equal Speed"
    else:
        return "High Speed"

In [18]:
def set_HP_values (value):
    if value < avg_hp:
        return "Low HP"
    elif value == avg_speed:
        return "Equal HP"
    else:
        return "High HP"

In [19]:
ds["High_Low_Speed"]= ds["Speed"].apply(set_speed_values)
ds["High_Low_HP"]= ds["HP"].apply(set_HP_values)

In [20]:
ds.head(n=15)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,High_Low_Speed,High_Low_HP
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Low Speed,Low HP
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Low Speed,Low HP
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,High Speed,High HP
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,High Speed,High HP
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Low Speed,Low HP
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,High Speed,Low HP
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,High Speed,High HP
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,High Speed,High HP
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,High Speed,High HP
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,Low Speed,Low HP
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False,Low Speed,Low HP
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False,High Speed,High HP
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False,High Speed,High HP
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False,Low Speed,Low HP
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False,Low Speed,Low HP